### ISSUE TITLE
Handle design

### ISSUE THREAD

**Issue by dvc94ch** [bytecodealliance/witx-bindgen#100]
So the current handle is works as follows:

1. the resource is owned by the vm and a destructor is registered
2. the host and targets both have a handle used to increment/decrement the ref count the vm stores
3. when the ref count goes to zero the vm invokes the destructor

I don't understand what the reasoning is behind this. wouldn't it be easier for the host to own the resource and call the destructor when appropriate?

**Comment by dvc94ch** [comment]
I guess it has to do with supporting gc'd languages inside of wasm, as otherwise the host could register the destructor with it's gc.

**Comment by alexcrichton** [comment]
I think issues like this are probably best opened on the WebAssembly/interface-types repository, this crate is intended to "simply implement" the standards there.
