### ISSUE TITLE
witx::Module without name leads to bad codegen with `RustWasm`

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/witx-bindgen#3]
If we use `witx::parse` to generate a `witx::Module` (internally uses a path `-`) from a string and feed that to the `Generator` impl for `RustWasm`, it will output an empty mod name and the generated code will fail to compile.

Perhaps `witx::parse` should take a file name or otherwise a setter for filename on `witx::Module` (with further validation on the `RustWasm` impl to ensure that name isn't empty when treated as an identifier)?

**Comment by sunfishcode** [comment]
I believe this is fixed with recent changes. The witx parser now requires modules read via `-` to have a name.
