### ISSUE TITLE
avoid get_export every time when guest code call into host function.

### ISSUE THREAD

**Issue by hh9527** [bytecodealliance/witx-bindgen#30]
Wasmer has a [WasmerEnv](https://docs.rs/wasmer/2.0.0/wasmer/trait.WasmerEnv.html) design to lazy init ctx when initialize instance. Is it possible to add this feature? 

This approach can avoid lookup `realloc` every time when guest code call into host function.

For example

```rust
      let func = get_func(&mut caller, "canonical_abi_realloc")?;
      let func_canonical_abi_realloc = func.typed::<(i32, i32, i32, i32), i32, _>(&caller)?;
      let memory = &get_memory(&mut caller, "memory")?;
```

could be

```rust
let lazy_ctx = get_lazy_ctx(caller)?; // get_func/get_memory only be called once when linking
let func_canonical_abi_realloc = lazy_ctx.func_canonical_abi_realloc;
let memory = lazy_ctx.memory;
```

**Comment by alexcrichton** [comment]
Thanks for the report! 

FWIW the codegen here is still, uh, very early-days. AFAIK nothing's actually using this in production yet. 

Have you tested this out locally and seen issues with the `get_func` calls in profiles?

**Comment by alexcrichton** [comment]
I'm going to close this for now since AFAIK we don't have a concrete reason to not do this, but if it's an issue please feel free to reopen or submit a new issue!
