### ISSUE TITLE
Bad codegen for resources with `witx_bindgen_wasmtime::import!`

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/witx-bindgen#33]
Using this witx:

```witx
resource foo {
    bar: function() -> string
}
```

for the macro invocation of `witx_bindgen_wasmtime::import!("foo.witx")` generates the following code:

```rust
mod foo {
    #[allow(unused_imports)]
    use witx_bindgen_wasmtime::{anyhow, wasmtime};
    pub trait Foo: Sized {
        type Foo: std::fmt::Debug;
        fn foo_bar(&mut self, self: () /* BUG: function already has a self parameter */) -> String;
        fn drop_foo(&mut self, state: Self::Foo) {
            drop(state);
        }
    }
    pub struct FooTables<T: Foo> {
        foo_table: witx_bindgen_wasmtime::Table<T::Foo>,
    }
    impl<T: Foo> Default for FooTables<T> {
        fn default() -> Self {
            Self {
                foo_table: Default::default(),
            }
        }
    }
    pub fn add_foo_to_linker<T, U>(
        linker: &mut wasmtime::Linker<T>,
        get: impl Fn(&mut T) -> (&mut U, &mut FooTables<U>) + Send + Sync + Copy + 'static,
    ) -> anyhow::Result<()>
    where
        U: Foo,
    {
        use witx_bindgen_wasmtime::rt::get_func;
        use witx_bindgen_wasmtime::rt::get_memory;
        linker.func_wrap(
            "foo",
            "foo::bar",
            move |mut caller: wasmtime::Caller<'_, T>, arg0: i32, arg1: i32| {
                let func = get_func(&mut caller, "canonical_abi_realloc")?;
                let func_canonical_abi_realloc =
                    func.typed::<(i32, i32, i32, i32), i32, _>(&caller)?;
                let memory = &get_memory(&mut caller, "memory")?;
                let host = get(caller.data_mut());
                let (host, _tables) = host;
                let param0 = _tables
                    .foo_table
                    .get((arg0) as u32)
                    .ok_or_else(|| wasmtime::Trap::new("invalid handle index"))?;
                () // BUG: return type is Result<()>
            },
        )?;
        linker.func_wrap(
            "canonical_abi",
            "resource_drop_foo",
            move |mut caller: wasmtime::Caller<'_, T>, handle: u32| {
                let (host, tables) = get(caller.data_mut());
                let handle = tables.foo_table.remove(handle).map_err(|e| {
                    wasmtime::Trap::new({
                        let res = ::alloc::fmt::format(::core::fmt::Arguments::new_v1(
                            &["failed to remove handle: "],
                            &match (&e,) {
                                (arg0,) => [::core::fmt::ArgumentV1::new(
                                    arg0,
                                    ::core::fmt::Display::fmt,
                                )],
                            },
                        ));
                        res
                    })
                })?;
                host.drop_foo(handle);
                Ok(())
            },
        )?;
        Ok(())
    }
    use witx_bindgen_wasmtime::rt::RawMem;
}
```

There are two bugs here:

* The trait implementation for `foo::bar` already has a self parameter, but the code is generating another `self` for what should be the resource being passed in (which appears to have type `()` and not `&Self::Foo`? that also seems incorrect).
* The generated host function for `foo::bar` returns `()` when the closure implicitly returns `Result<_>`.

**Comment by peterhuene** [comment]
On an aside, it seems a little backwards to me that I would use `witx_bindgen_wasmtime::import!` to *export* these functions from a host to a Wasm module (which might use `witx_bindgen_rust::import!` itself to import these functions).

I initially expected to use `witx_bindgen_wasmtime::export!`, to be honest.

**Comment by alexcrichton** [comment]
Heh I was actually about to fix this originally when I realized that resources barely worked at all, so I ended up getting distracted getting exported resources working entirely first.

My goal was to soon move on to nested resources like this and fix up all the issues here. I think there's probably quite a few issues lurking here, but I'm hoping it's not too too hard to fix.

I'd like to use method patterns where possible as well (for both imports and exports), so that will likely take some finagling to get that working.

> On an aside, it seems a little backwards to me ...

Yeah I'm by no means good at naming things. The intention right now is that `import!` binds the imports of the wasm module, and `export!` binds the exports. I think your confusion is pretty reasonable though.

Overally I don't like the import/export terminology. In general I don't like the idea of splitting things, from the perspective of users, into import/export. Let me actually open an issue on this...

**Comment by peterhuene** [comment]
There's no rush on this.

I figured I'd update `wasmtime-functions` to latest Wasmtime and replace the wiggle-based host impl with `witx-bindgen` and the new witx syntax (especially as using resources to describe requests and responses is sooo much nicer than what it uses now) so that there would be more examples of using witx-bindgen out there.
