### ISSUE TITLE
No memory export for linked module with transitive imports

### ISSUE THREAD

**Issue by radu-matei** [bytecodealliance/witx-bindgen#51]
I have the following import structure: executable -> cache -> wasi_object_storage.

`wasmlink` does generate a linked module:

```
wasmlink -i cache=cache.wasm -i wasi_object_storage=wasi_object_storage.wasm -p wasmtime -o linked.wasm executable.wasm
```

But the module fails to compile because of the missing memory export:

```
wasmtime --enable-module-linking --enable-multi-memory linked.wasm Error: failed to run main module `linked.wasm`
Caused by:
    0: WebAssembly failed to compile
    1: WebAssembly translation error
    2: Invalid input WebAssembly code at offset 5539697: no export named `memory`
```

**Comment by peterhuene** [comment]
Hi @radu-matei. If possible, could you share the wasm files with me (phuene@fastly.com)?  It's probably just a problem with reexporting something from an adapted module.  Thanks!

**Comment by peterhuene** [comment]
This is a problem with how the we shim modules to instantiate them to try to solve an ordering problem introduced by module linking (namely that the local index space for functions isn't visible to an instantiation so we can't import them directly).

The implemented solution is inadequate when the intermediary module *is also adapted* and needs an import of its parent's memory.

I'll see what I can do to implement a fix.

**Comment by peterhuene** [comment]
So the fix is far less complicated than I originally thought as we don't have to change how the adapted modules are shim'ed at all.

The problem is actually that the adapted module doesn't re-export the original module's memory or the canonical ABI functions so that it can be properly utilized from *another* adapted module.

Fix incoming.
