### ISSUE TITLE
Integer-only datatypes get conflicting Endian implementation

### ISSUE THREAD

**Issue by itowlson** [bytecodealliance/witx-bindgen#63]
If I generate from the following WITX file:

```
type timestamp = u32

type input = tuple<timestamp>
type output = u32

handler: function(e: input) -> output
```

then the generated Rust bindings have the following implementations:

```rust
  impl witx_bindgen_wasmtime::Endian for Input {
    // ...
  }
  unsafe impl witx_bindgen_wasmtime::AllBytesValid for Input {}
```

both of which cause a 'conflicting implementations' error:

```
conflicting implementations of trait `witx_bindgen_wasmtime::Endian` for type `(u32,)`
conflicting implementations of trait `witx_bindgen_wasmtime::AllBytesValid` for type `(u32,)`
```

If I add a `string` to the tuple then the error goes away.

**ETA:** This is using the Wasmtime `export` generator.

**Comment by alexcrichton** [comment]
Thanks for the report! This is indeed a bug and a case where those trait implementations shouldn't be synthesized for custom types, I'll see to fix this today.
