### ISSUE TITLE
Unable to parse the wasi witx definitions

### ISSUE THREAD

**Issue by bjorn3** [bytecodealliance/witx-bindgen#67]
https://bytecodealliance.github.io/witx-bindgen/

```
extra tokens remaining after parse
     --> input:8:1
      |
    8 | (typename $size u32)
      | ^
```

**Comment by bjorn3** [comment]
Ah, the `old-witx-compat` feature of `witx-bindgen-gen-core` needs to be enabled for it to work.

**Comment by alexcrichton** [comment]
Yes the exact syntax parsed by this right now is different than the current s-expression syntax slightly. I think some changes were reverted on the WASI repo and I didn't reflect those changes here. The syntax is enabled, though, for example you can see with:

```
(module $x
    (typename $a u32)
)
```

in the online preview.

**Comment by bjorn3** [comment]
Yeah, it works. I do need to rename the `$fd` resource though to avoid the above error and then it crashes when trying to generate js:

```
panicked at 'called `Option::unwrap()` on a `None` value', crates/gen-js/src/lib.rs:1577:74
    error https://bytecodealliance.github.io/witx-bindgen/browser/bindings.js:14
    Config$GT$3new28_$u7b$$u7b$closure$u7d$$u7d$28_$u7b$$u7b$closure$u7d$$u7d$17hc3548f0a0e19d9b8E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:21495
    _ZN3std9panicking20rust_panic_with_hook17h2d9079427a2d996aE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1238878
    _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h4e49f350d9f4de36E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1235338
    _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h91e711607d91be52E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1235193
    rust_begin_unwind https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1238631
    _ZN4core9panicking9panic_fmt17h1fea623755fffed7E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1246871
    _ZN4core9panicking5panic17h38cac710b5048ca0E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:1243875
    Bindgen$GT$4emit17hc14e5c5c3ef64090E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:641662
    _ZN5witx23abi18Generator$LT$B$GT$4emit17h29e995f42a9bba15E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:683197
    _ZN5witx23abi18Generator$LT$B$GT$4lift17ha82fa66619137e3cE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:689112
    _ZN5witx23abi18Generator$LT$B$GT$8lift_all17h900e8d3422513b3fE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:703981
    _ZN5witx23abi18Generator$LT$B$GT$4call17h002cf80a6b6f2a58E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:701440
    Interface$GT$4call17h4b1056d7b69908f3E https://bytecodealliance.github.io/witx-bindgen/demo.wasm:665379
    Generator$GT$6import17h7c00bc37a10c78aeE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:598427
    _ZN21witx_bindgen_gen_core9Generator8generate17h8c254e199c99850fE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:35853
    Config$GT$6render17hb8945f660c715d4fE https://bytecodealliance.github.io/witx-bindgen/demo.wasm:17252
    render https://bytecodealliance.github.io/witx-bindgen/demo.wasm:27402
```

**Comment by sambitnayak** [comment]
Hoping this is a related query, else please point me to the right forum/issue.

Can *witx-bindgen* be used to generate Python (*wasmtime-py*) host bindings for [*wasi-nn*](https://github.com/WebAssembly/wasi-nn/blob/main/phases/ephemeral/witx/wasi_ephemeral_nn.witx) witx?

I'm getting errors like the one posted in this issue, and reading through these details, I want to check if this is supported at all?

Otherwise, if not *witx-bindgen*, could you please tell what is the best way to provide Python host-side functions in a Python program embedding *wasmtime-py*, that will satisfy something like the *wasi-nn* witx required by a Wasm guest module?

**Comment by alexcrichton** [comment]
@bjorn3 can you open a separate issue specifically for the JS error you're seeing?

@sambitnayak yes it's supported, but the s-expression-based syntax is not precisely the same as the one supported by the `witx` crate at this time. It diverged at some point and I haven't gotten around to trying to fix it.

For reference all implementations are tested against [wasi snapshot](https://github.com/bytecodealliance/witx-bindgen/tree/main/tests/wasi_snapshot_preview1) as well as [a version of wasi purely using interface types](https://github.com/bytecodealliance/witx-bindgen/tree/main/tests/wasi-next) so it's not like things aren't supported and/or don't work, it's probably just fiddly syntax.

**Comment by bjorn3** [comment]
> @bjorn3 can you open a separate issue specifically for the JS error you're seeing?

Done: https://github.com/bytecodealliance/witx-bindgen/issues/69
