### ISSUE TITLE
support generating cffi's

### ISSUE THREAD

**Issue by dvc94ch** [bytecodealliance/witx-bindgen#99]
briefly considered using wasi, but it simply isn't there yet. witx-bindgen seems usable for `wasm32-unknown-unknown`, and I think it may be suitable to generate a cffi and bindings using a higher level api than what is possible using a c header. any thoughts on if this would be considered upstream? might give it a go next week. (mainly interested in interfacing with dart/flutter and maybe kotlin/swift).

**Comment by alexcrichton** [comment]
Thanks for the report, but can you clarify what you're asking for here? There's already generation modes for C right now (see the `crates/gen-c` generator), but are you thinking that this should support non-wasm language bindings?

**Comment by dvc94ch** [comment]
>  are you thinking that this should support non-wasm language bindings?

exactly, yes. looks like the interface specification isn't specific to wasm.

**Comment by dvc94ch** [comment]
basically the use case I have is we're building a rust p2p networking/crdt library that will be packaged for use in popular frontend frameworks like flutter/react. looks like witx-bindgen could help us keep the different language bindings in sync and avoid some error prone and tedious boilerplate.

**Comment by alexcrichton** [comment]
Ah ok thanks for the clarification. In that case though I'm going to close this as out of scope for this project for now. While one day witx and friends may make cross-language communication easier than just for wasm but also for all embeddings it's an extremely ambitious project and we've got enough to figure out today with just wasm. Perhaps in the future having a tracking issue for this or a demo implementation, but for now there's too much else to do.

**Comment by dvc94ch** [comment]
So we'll be using it for the wasm32-unknown-unknown target and I'll look into forking it and replacing our cffi/dart bindings.

**Comment by dvc94ch** [comment]
so got it working, except for the async feature. the required changes are:

- support for i64 pointers
- fix prefixing/namespace inconsistency
- support passing RET_AREA as an argument
- handle needs some kind of redesign

looks like getting non-wasm support isn't that far off
